{
 "title": "ntopng",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ifid", "label": "Interface" }
  ]
 },
 "panels": [
  { "title": "Top Talkers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incoming Top Talkers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"ntopng/autogen\") \n  |> range($range) \n  |> filter(fn: (r) => r._measurement == \"host:traffic\" and (r._field == \"bytes_rcvd\") and (r.ifid == \"$ifid\")) \n  |> difference(nonNegative: true) \n  |> sum() \n  |> group() \n  |> top(n:10)\n  |> duplicate(column: \"host\", as: \"_field\") \n  |> group(columns: [\"_field\"]) \n  |> drop(columns: [\"_measurement\",\"ifid\", \"host\"])"
    }
   ]
  },
  {
   "title": "Outgoing Top Talkers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"ntopng/autogen\") \n  |> range($range) \n  |> filter(fn: (r) => r._measurement == \"host:traffic\" and (r._field == \"bytes_sent\") and (r.ifid == \"$ifid\")) \n  |> difference(nonNegative: true) \n  |> sum() \n  |> group() \n  |> top(n:10)\n  |> duplicate(column: \"host\", as: \"_field\") \n  |> group(columns: [\"_field\"]) \n  |> drop(columns: [\"_measurement\",\"ifid\", \"host\"])"
    }
   ]
  },
  {
   "title": "Top Incoming Traffic by IP and port",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "query": "from(bucket: \"ntopng/autogen\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"host:ndpi\" and (r._field == \"bytes_rcvd\") and (r.ifid == \"$ifid\"))\n  |> group (columns: [\"host\",\"protocol\"])\n  |> difference(nonNegative: true)\n  |> sum()\n  |> group()\n  |> top(n:50)\n  |> group(columns:[\"host\",\"protocol\"])"
    }
   ]
  },
  {
   "title": "Top Outgoing Traffic by IP and port",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "query": "from(bucket: \"ntopng/autogen\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"host:ndpi\" and (r._field == \"bytes_sent\") and (r.ifid == \"$ifid\"))\n  |> group (columns: [\"host\",\"protocol\"])\n  |> difference(nonNegative: true)\n  |> sum()\n  |> group()\n  |> top(n:50)\n  |> group(columns:[\"host\",\"protocol\"])"
    }
   ]
  },
  {
   "title": "Traffic By Source Country",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic By Source Country",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 11, "w": 22, "x": 1, "y": 10 },
     "valueName": "total",
     "targets": [
      {
       "alias": "$tag_country",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "country" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "country:traffic",
       "query": "select non_negative_difference(sum(\"bytes_ingress\"))/1000000000 as \"bytes\" from  \"country:traffic\" WHERE (\"ifid\" =~ /^$ifid$/) AND $timeFilter GROUP BY time(1s),country",
       "select": [
        [
         { "params": [ "bytes_ingress" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ " / 1000000000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "ifid", "operator": "=~", "value": "/^$ifid$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic By Destination Port",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "query": "from(bucket: \"ntopng/autogen\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"iface:ndpi\" and (r._field == \"bytes\") and (r.ifid ==\"$ifid\"))\n  |> group(columns: [\"protocol\"])\n  |> difference(nonNegative: true)\n  |> sum()\n  |> group()\n  |> top(n:20)\n  |> duplicate(column: \"protocol\", as: \"_field\")\n  |> group(columns: [\"_field\"])\n  |> drop(columns: [\"protocol\"])"
      }
     ]
    }
   ]
  },
  {
   "title": "Layer 4 Ingress Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Layer 4 Traffic Breakdown",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "query": "from(bucket: \"ntopng/autogen\") \n  |> range($range) \n  |> filter(fn: (r) => r._measurement == \"iface:l4protos\" and (r.ifid == \"$ifid\")) \n  |> group(columns: [\"l4proto\"]) \n  |> difference(nonNegative: true) \n  |> sum()\n  |> duplicate(column: \"l4proto\", as: \"_field\") \n  |>group() \n  |> drop (columns: [\"l4proto\"]) \n  |> group(columns: [\"_field\"])\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Threat Score",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host Traffic Score",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "query": "from(bucket: \"ntopng/autogen\") |> range($range) |> filter(fn: (r) => r._measurement == \"host:score\" and (r.ifid == \"$ifid\")) |> max() |> group() |> top (n:10) |> duplicate(column: \"host\", as: \"_field\") |> group(columns: [\"host\"]) |> drop(columns: [\"_measurement\",\"ifid\",\"host\"])"
      }
     ]
    }
   ]
  }
 ]
}